PRETRAINED_PATH = "hgnetv2_b0.pth"
IMG_DIR = "geo_dataset/train"
OUT_DIR = "outputs/run"

TIMM_ARCH = "hgnetv2_b0"
IMAGE_SIZE = 512
TARGET_SIZE = 512
AUG_SPEC = {"crop": False}
AUGMENT = True

BATCH_SIZE = 64
NUM_WORKERS = 4
LR = 3e-4
WEIGHT_DECAY = 1e-3
DROPOUT = 0.3
GRAD_CLIP = 5.0
MAX_EPOCHS = 100
PATIENCE = 10
MIN_DELTA = 0.5

SEED = 42
GEOCELL_SEED = 42

N_CELLS = 64
N_CELLS_FINE = 256
REG_SCALE_KM = 100.0
UNCERTAINTY_INIT_LAMBDA = 1.0
LABEL_SMOOTH_KM = 25.0

PREDICTOR = "retrieval"
ANCHOR_TOPK = 3
